local activityData = {
	{ factor=0, name="Аэробика", category=1 },
	{ factor=5, name="Аэробика, низкая нагрузка", category=0 },
	{ factor=6.5, name="Аэробика, средняя нагрузка", category=0 },
	{ factor=7, name="Аэробика, высокая нагрузка", category=0 },
	{ factor=8.5, name="Степ-аэробика, платформа 15-20 см", category=0 },
	{ factor=10, name="Степ-аэробика, платформа 25-30 см", category=0 },

	{ factor=0, name="Активный отдых", category=1 },
	{ factor=4.5, name="Бадминтон", category=0 },
	{ factor=7, name="Дайвинг", category=0 },
	{ factor=8.8, name="Зумба фитнес", category=0 },
	{ factor=3, name="Игра с фрисби", category=0 },
	{ factor=2.5, name="Йога", category=0 },
	{ factor=2.5, name="Катание на лошади", category=0 },
	{ factor=12, name="Катание на роликах", category=0 },
	{ factor=5, name="Катание на скейте", category=0 },
	{ factor=5, name="Охота", category=0 },
	{ factor=3, name="Прыжки в воду", category=0 },
	{ factor=3, name="Сёрфинг", category=0 },
	{ factor=5, name="Сплав по горной реке", category=0 },

	{ factor=0, name="Бег", category=1 },
	{ factor=8, name="Бег, 8 км/ч", category=0 },
	{ factor=8.5, name="Бег, 8.5 км/ч", category=0 },
	{ factor=10, name="Бег, 9.5 км/ч", category=0 },
	{ factor=11, name="Бег, 10.5 км/ч", category=0 },
	{ factor=11.5, name="Бег, 11 км/ч", category=0 },
	{ factor=12.5, name="Бег, 12 км/ч", category=0 },
	{ factor=13.5, name="Бег, 13 км/ч", category=0 },
	{ factor=14, name="Бег, 14 км/ч", category=0 },
	{ factor=15, name="Бег, 15 км/ч", category=0 },
	{ factor=16, name="Бег, 16 км/ч", category=0 },
	{ factor=18, name="Бег, 17 км/ч", category=0 },
	{ factor=8, name="Бег на месте", category=0 },
	{ factor=15, name="Бег по лестнице", category=0 },
	
	{ factor=0, name="Велосипед", category=1 },
	{ factor=4, name="Велосипед, < 15 км/ч", category=0 },
	{ factor=6, name="Велосипед, 15-20 км/ч", category=0 },
	{ factor=8, name="Велосипед, 20-25 км/ч", category=0 },
	{ factor=10, name="Велосипед, 25-30 км/ч", category=0 },
	{ factor=12, name="Велосипед, 30-35 км/ч", category=0 },
	{ factor=16, name="Велосипед, > 35 км/ч", category=0 },
	{ factor=8.5, name="Велосипед, горный или BMX", category=0 },

	{ factor=0, name="Дом", category=1 },
	{ factor=6, name="Передвижение мебели", category=0 },
	{ factor=7, name="Перетаскивание коробок", category=0 },
	{ factor=9, name="Перетаскивание коробок по лестнице", category=0 },
	{ factor=2, name="Приготовление еды", category=0 },
	{ factor=3, name="Уборка дома", category=0 },

	{ factor=0, name="Музыка", category=1 },
	{ factor=4, name="Игра на барабанах", category=0 },
	{ factor=2, name="Игра на духовых инструментах", category=0 },
	{ factor=2.5, name="Игра на клавишных", category=0 },
	{ factor=2, name="Игра на струнных инструментах", category=0 },
	{ factor=3, name="Игра на электрогитаре стоя", category=0 },

	{ factor=0, name="Плавание", category=1 },
	{ factor=11, name="Плавание баттерфляем", category=0 },
	{ factor=10, name="Плавание брассом", category=0 },
	{ factor=10, name="Плавание кролем, быстрое", category=0 },
	{ factor=7, name="Плавание кролем, среднее", category=0 },
	{ factor=5, name="Плавание кролем, медленное", category=0 },
	{ factor=4, name="Плавание на месте", category=0 },
	{ factor=7, name="Плавание на спине", category=0 },
	{ factor=8, name="Синхронное плавание", category=0 },
	{ factor=5, name="Сноркелинг", category=0 },

	{ factor=0, name="Работа", category=1 },
	{ factor=5.5, name="Стрижка газона", category=0 },
	{ factor=5, name="Копание земли", category=0 },
	{ factor=4.5, name="Посадка деревьев", category=0 },
	{ factor=4, name="Работа в огороде", category=0 },
	{ factor=4.3, name="Работа граблями", category=0 },
	{ factor=3, name="Ремонт автомобиля", category=0 },
	{ factor=6.2, name="Рубка дров", category=0 },
	{ factor=3, name="Столярное дело", category=0 },
	{ factor=6.2, name="Уборка снега", category=0 },
	
	{ factor=0, name="Рыбалка", category=1 },
	{ factor=2.5, name="Рыбалка с лодки, сидя", category=0 },
	{ factor=3.5, name="Рыбалка на берегу реки, стоя", category=0 },
	{ factor=6, name="Рыбалка в реке, в сапогах", category=0 },
	{ factor=3, name="Рыбалка в целом", category=0 },
	{ factor=2, name="Подлёдная рыбалка, сидя", category=0 },

	{ factor=0, name="Секс", category=1 },
	{ factor=1.1, name="Сексуальная активность, лёгкая", category=0 },
	{ factor=1.3, name="Сексуальная активность, средняя", category=0 },
	{ factor=1.5, name="Сексуальная активность, энергичная", category=0 },
	
	{ factor=0, name="Спорт", category=1 },
	{ factor=7, name="Альпинизм", category=0 },
	{ factor=8, name="Американский футбол", category=0 },
	{ factor=8, name="Баскетбол", category=0 },
	{ factor=6, name="Бейсбол", category=0 },
	{ factor=2.5, name="Бильярд", category=0 },
	{ factor=8.8, name="Боевые искусства", category=0 },
	{ factor=12, name="Бокс, соревнование", category=0 },
	{ factor=9, name="Бокс, спарринг", category=0 },
	{ factor=6, name="Бокс, удары по груше", category=0 },
	{ factor=7, name="Большой теннис", category=0 },
	{ factor=3, name="Боулинг", category=0 },
	{ factor=10, name="Водное поло", category=0 },
	{ factor=7, name="Волейбол", category=0 },
	{ factor=6.2, name="Вольная борьба", category=0 },
	{ factor=6, name="Гандбол", category=0 },
	{ factor=2.5, name="Дартс", category=0 },
	{ factor=10, name="Дзю-до, карате, кикбоксинг", category=0 },
	{ factor=5, name="Каякинг", category=0 },
	{ factor=4, name="Кёрлинг", category=0 },
	{ factor=4, name="Мотокросс", category=0 },
	{ factor=4, name="Настольный теннис", category=0 },
	{ factor=8, name="Пляжный волейбол", category=0 },
	{ factor=10, name="Регби", category=0 },
	{ factor=8, name="Скалолазание", category=0 },
	{ factor=12, name="Сквош", category=0 },
	{ factor=6.2, name="Сноубординг", category=0 },
	{ factor=3.5, name="Стрельба из лука", category=0 },
	{ factor=6, name="Фехтование", category=0 },
	{ factor=7, name="Футбол", category=0 },
	{ factor=8, name="Хоккей на льду", category=0 },
	{ factor=8, name="Хоккей на траве", category=0 },
	{ factor=7, name="Фигурное катание", category=0 },

	{ factor=0, name="Танцы", category=1 },
	{ factor=4.8, name="Балет", category=0 },
	{ factor=3, name="Бальные танцы, медленные", category=0 },
	{ factor=5.5, name="Бальные танцы, быстрые", category=0 },
	{ factor=5, name="Брейк-данс", category=0 },
	{ factor=4.8, name="Латинские танцы", category=0 },
	{ factor=4.5, name="Танец живота", category=0 },
	{ factor=4.8, name="Танец модерн", category=0 },

	{ factor=0, name="Тренажёры", category=1 },
	{ factor=3, name="Велотренажёр, очень лёгкая нагрузка", category=0 },
	{ factor=5.5, name="Велотренажёр, лёгкая нагрузка", category=0 },
	{ factor=7, name="Велотренажёр, средняя нагрузка", category=0 },
	{ factor=10.5, name="Велотренажёр, высокая нагрузка", category=0 },
	{ factor=12.5, name="Велотренажёр, очень высокая нагрузка", category=0 },
	{ factor=9, name="Тренажёр «Ходьба по лестнице»", category=0 },
	{ factor=9, name="Эллиптический тренажёр", category=0 },
	
	{ factor=0, name="Тренировки", category=1 },
	{ factor=4.5, name="Броски по баскетбольному кольцу", category=0 },
	{ factor=4, name="Гимнастика", category=0 },
	{ factor=8, name="Круговая тренировка", category=0 },
	{ factor=7.9, name="Приседания", category=0 },
	{ factor=12, name="Прыжки со скакалкой, быстро", category=0 },
	{ factor=8, name="Прыжки со скакалкой, медленно", category=0 },
	{ factor=10, name="Прыжки со скакалкой, средне", category=0 },
	{ factor=2.5, name="Растяжка", category=0 },
	{ factor=3, name="Силовой тренинг", category=0 },
	{ factor=8.3, name="Прыжки с руками над головой", category=0 },
	
	{ factor=0, name="Ходьба", category=1 },
	{ factor=2.5, name="Ходьба, 3 км/ч", category=0 },
	{ factor=2.8, name="Ходьба в гору, 3 км/ч", category=0 },
	{ factor=3, name="Ходьба, 4 км/ч", category=0 },
	{ factor=3.3, name="Ходьба, 5 км/ч", category=0 },
	{ factor=3.8, name="Ходьба, 5.5 км/ч", category=0 },
	{ factor=6, name="Ходьба в гору, 5.5 км/ч", category=0 },
	{ factor=5, name="Ходьба 6 км/ч", category=0 },
	{ factor=6.3, name="Ходьба 7 км/ч", category=0 },
	{ factor=8, name="Ходьба 8 км/ч", category=0 },
	{ factor=3.5, name="Ходьба с младенцем", category=0 },
	{ factor=8, name="Подъём по лестнице", category=0 },
	{ factor=6.5, name="Спортивная ходьба", category=0 },
	{ factor=6, name="Ходьба по пересечённой местности", category=0 },
	{ factor=2.5, name="Прогулка с детской коляской", category=0 },
}

return activityData;